---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.11
  - name: ubuntu-12.04
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: fedora-25

suites:
  - name: default
    run_list:
      - recipe[lldpad::default]
    attributes:
      lldpad:
        install_on_vm_guest: true

